language: python
sudo: false
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
env:
 - DJANGO_VERSION=1.8
 - DJANGO_VERSION=1.9
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.9
    - python: "3.3"
      env: DJANGO_VERSION=1.9
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
 - pip install -q flake8
script:
 - ./run.sh test
 - ./run.sh check
