language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.9
 - DJANGO_VERSION=1.5.5
 - DJANGO_VERSION=1.6c1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.9
    - python: "3.3"
      env: DJANGO_VERSION=1.4.9
install:
 - pip install -q git+https://github.com/django/django.git@${DJANGO_VERSION}#egg=Django
script: ./run.sh test
