language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
env:
 - DJANGO_VERSION=1.8
 - DJANGO_VERSION=1.10
 - DJANGO_VERSION=1.11
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO_VERSION=1.8
    - python: "3.3"
      env: DJANGO_VERSION=1.10
    - python: "3.6"
      env: DJANGO_VERSION=1.10
    - python: "3.3"
      env: DJANGO_VERSION=1.11
    - python: "3.4"
      env: DJANGO_VERSION=1.11
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
 - pip install -q flake8 coverage
script:
 - ./run.sh coverage
 - ./run.sh check
