language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.12
 - DJANGO_VERSION=1.5.7
 - DJANGO_VERSION=1.6.4
 - DJANGO_VERSION=1.7b3
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.12
    - python: "3.3"
      env: DJANGO_VERSION=1.4.12
    - python: "2.6"
      env: DJANGO_VERSION=1.7b3
install:
 - pip install -q git+https://github.com/django/django.git@${DJANGO_VERSION}#egg=Django
script: ./run.sh test
