language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
env:
 - DJANGO_VERSION=1.4.8
 - DJANGO_VERSION=1.5.4
install:
 - pip install -q Django==${DJANGO_VERSION} --use-mirrors
script: ./run.sh test
