language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "pypy"
env:
 - DJANGO_VERSION=1.4
 - DJANGO_VERSION=1.6
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.4
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
 - pip install -q flake8
script:
 - ./run.sh test
 - ./run.sh check
