language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
env:
 - DJANGO_VERSION=1.4
 - DJANGO_VERSION=1.5
 - DJANGO_VERSION=1.6
 - DJANGO_VERSION=1.7
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "2.6"
      env: DJANGO_VERSION=1.7
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
script: ./run.sh test
